### ISSUE TITLE
Can I use OEC database to do the calculation?

### ISSUE THREAD

**Issue by complexly** [alexandersimoes/ps_calcs#2]
Thank you first for sharing these codes!

I'm working on a project related to product space, and trying to replicate the results. Currently I have downloaded and imported the sql dump of oec, can I use that data for calculation? If so, can I use a 4-digit "hs_yop" instead of  "observatory_hs4_cpy"? If not, could you introduce some pre-processing steps or research papers? Thanks!

**Comment by alexandersimoes** [comment]
You can use the dumps from the live OEC database -- http://atlas.media.mit.edu/en/resources/data/

**Comment by alexandersimoes** [comment]
It would be helpful to have some boilerplate code here, see #3
